code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension BeardedBear.beardedtheme
code --install-extension bierner.emojisense
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension cdonohue.quill-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElAnandKumar.el-vsc-product-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension jabacchetta.material-pro
code --install-extension JackLaFond.annie-dark
code --install-extension karyfoundation.nearley
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension Nuxt.mdc
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pmndrs.pmndrs
code --install-extension pmneo.tsimporter
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension sallar.vscode-duotone-dark
code --install-extension samogorman1993.space-invader
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension solomonkinard.case-flip
code --install-extension SPGoding.datapack-language-server
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension Vue.volar
code --install-extension zamerick.vscode-caddyfile-syntax
